services:
  cron-service:
    build: .
    container_name: taxi
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/Warsaw
      - PYTHONUNBUFFERED=1
    volumes:
      - type: bind
        source: ${WEBAPP_STORAGE_HOME:-.}/logs
        target: /logs
    depends_on:
      - mqtt
    image: ghcr.io/sborys00/taxi-simulator:latest

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1833:1883
      - 9001:9001
    volumes:
      - type: bind
        source: ${WEBAPP_STORAGE_HOME:-.}/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
networks:
  default:
    name: shared-network
