services:
  simulator-service:
    build: .
    container_name: simulator-service
    ports:
      - "8081:8081"
    environment:
      - TZ=Europe/Warsaw
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/logs
