services:
  cron-service:
    build: .
    container_name: taxi
    ports:
      - "8081:8081"
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1833:1883
      - 9001:9001
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  