export { default as Home } from "./home/Home.tsx"
export { default as Map } from "./map/Map.tsx"
export { default as Taxi } from "./taxi/Taxis.tsx"
export { default as Drivers } from "./drivers/Drivers.tsx"
export { default as Courses } from "./courses/Courses.tsx"
export { default as Profile } from "./profile/Profile.tsx"
