version: '3.5'
services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      - POSTGRES_PASSWORD=taxi
      - POSTGRES_USER=taxi
      - POSTGRES_DB=testowa_baza
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    command: >
      sh -c "python3 /app/manage.py migrate &&
             python3 /app/manage.py loaddata /app/taxi_backend/seed/*.json &&
             python3 /app/manage.py runserver 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    image: ghcr.io/sborys00/taxi-backend:latest
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    name: shared-network
    external: true
