version: '3.5'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      - POSTGRES_PASSWORD=taxi
      - POSTGRES_USER=taxi
      - POSTGRES_DB=testowa_baza
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql

  web:
    build: .
    command: >
      sh -c "python3 manage.py makemigrations taxi_backend &&
             python3 manage.py makemigrations &&
             python3 /app/manage.py migrate &&
             python3 /app/manage.py loaddata /app/taxi_backend/seed/*.json &&
             python3 /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ../certs/backend/backend.key:/certs/backend.key:ro
      - ../certs/backend/backend.pem:/certs/backend.pem:ro
      - ../certs/ca/ca.pem:/certs/ca.pem:ro
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

networks:
  default:
    name: shared-network
    external: true
