# docker-compose.yml

version: '3.5'
services:
  # Usługi istniejącego pliku docker-compose.yml
  web:
    build: .
    command: sh -c "python3 /app/manage.py migrate && python3 /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      - POSTGRES_PASSWORD=taxi
      - POSTGRES_USER=taxi
      - POSTGRES_DB=testowa_baza
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres


  test:
    build: .
    command: sh -c "python3 /app/manage.py test"
    depends_on:
      - postgres