version: '3.5'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    restart: always
    environment:
      - POSTGRES_PASSWORD=taxi
      - POSTGRES_USER=taxi
      - POSTGRES_DB=testowa_baza
    ports:
      - 5432:5432
    volumes:
      - ${WEBAPP_STORAGE_HOME:-.}/data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    image: ghcr.io/sborys00/taxi-backend:latest
    command: >
      sh -c "python3 manage.py makemigrations taxi_backend &&
             python3 manage.py makemigrations &&
             python3 /app/manage.py migrate &&
             python3 /app/manage.py loaddata /app/taxi_backend/seed/*.json &&
             python3 /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ../certs/backend/backend.key:/certs/backend.key:ro
      - ../certs/backend/backend.pem:/certs/backend.pem:ro
      - ../certs/ca/ca.pem:/certs/ca.pem:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

networks:
  default:
    name: shared-network
    external: true
  