name: Build and push images

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: sborys00

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./simulator
            image: $REGISTRY/$REGISTRY_USERNAME/taxi-simulator
          - dockerfile: ./taxi-backend
            image: $REGISTRY/$REGISTRY_USERNAME/taxi-backend
          - dockerfile: ./taxi-frontend
            image: $REGISTRY/$REGISTRY_USERNAME/taxi-frontend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}